### ISSUE TITLE
Assertion Error with del_series

### ISSUE THREAD

**Issue by CodedNil** [totaldebug/pyarr#110]
When I run sonarrapi.del_series(id, delete_files=True) I get this error:
Traceback (most recent call last):
  File "/home/dan/Sheetarr/sheetarr.py", line 657, in <module>
    sonarrapi.del_series(id, delete_files=True)
  File "/home/dan/.local/lib/python3.9/site-packages/pyarr/sonarr.py", line 478, in del_series
    return self._delete(f"series/{id_}", self.ver_uri, params=params)
  File "/home/dan/.local/lib/python3.9/site-packages/pyarr/request_handler.py", line 189, in _delete
    return self._return(res, Response)
  File "/home/dan/.local/lib/python3.9/site-packages/pyarr/request_handler.py", line 202, in _return
    assert isinstance(response, arg1)
AssertionError

The series is successfully deleted from sonarr though

**Comment by marksie1988** [comment]
After some investigation, it looks like sonarr responds with  an empty dict `{}` to a delete where as others return a `200 ok` 

Will try re-work the assertions for this and get an update out shortly.
