### ISSUE TITLE
AssertionError with get_series()

### ISSUE THREAD

**Issue by stancubed** [totaldebug/pyarr#124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behaviour

When I run sonarr.get_series(id) I get the below error (see bottom of post). I can successfully run sonarr.get_series() with no arguments and I'm provided a list of series, but providing an INT id is causing it to fail this way. The specific call I am trying to make is:
```sonarr.get_series(207)```

That seriesID is being returned by another function and it appears to be valid, but I'm not able to specifically get the series at this point.

Traceback being received:
```
Traceback (most recent call last):
  File "/home/stanstanstan/.local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/stanstanstan/.local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/stanstanstan/.local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/stanstanstan/.local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/stanstanstan/flask-calendar/app.py", line 35, in sonarr
    pprint(sonarr.get_series(209))
  File "/home/stanstanstan/.local/lib/python3.9/site-packages/pyarr/sonarr.py", line 422, in get_series
    return self.assert_return(path, self.ver_uri, list)
  File "/home/stanstanstan/.local/lib/python3.9/site-packages/pyarr/base.py", line 47, in assert_return
    assert isinstance(response, typearg)
AssertionError
```

### Expected behaviour

API returns a single result, matching the ID provided.

### Steps To Reproduce

```
def sonarr_example():
    host_url = 'http://redacted.site.url'
    api_key = 'xxxxxxxxxxxxxxxxxxxxxxxx'
    sonarr = SonarrAPI(host_url, api_key)
    
    pprint(sonar.get_series()) # Works!
    pprint(sonarr.get_series(209)) # Results in traceback...
    series = sonarr.get_series(id_=209) # Also results in traceback...
    
    return "OK"
```

### Pyarr Version

2.0 (I believe according to the docs. Latest version though.)

### Python Version

Python 3.9.2

### Example Code

```shell
def sonarr_example():
    host_url = 'http://redacted.site.url'
    api_key = 'xxxxxxxxxxxxxxxxxxxxxxxx'
    sonarr = SonarrAPI(host_url, api_key)
    
    pprint(sonar.get_series()) # Works!
    pprint(sonarr.get_series(209)) # Results in traceback...
    series = sonarr.get_series(id_=209) # Also results in traceback...
    
    return "OK"
```
```


### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/stanstanstan/.local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/stanstanstan/.local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/stanstanstan/.local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/stanstanstan/.local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/stanstanstan/flask-calendar/app.py", line 35, in sonarr
    pprint(sonarr.get_series(209))
  File "/home/stanstanstan/.local/lib/python3.9/site-packages/pyarr/sonarr.py", line 422, in get_series
    return self.assert_return(path, self.ver_uri, list)
  File "/home/stanstanstan/.local/lib/python3.9/site-packages/pyarr/base.py", line 47, in assert_return
    assert isinstance(response, typearg)
AssertionError
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
I would recommend downgrading the version to one of the 3.x versions of the library. 

Type hints were added but later found some issues with this. I am currently working on a PR to resolve this but it's taking a while as I'm also adding tests to stop this happening on future releases.

**Comment by stancubed** [comment]
Am I not using the correct type for this? Or do you know what the root cause is and type hints would just help explain it?

**Comment by marksie1988** [comment]
Some of the types that were implemented were incorrect, these are being corrected in this PR https://github.com/totaldebug/pyarr/pull/116

However not expecting to release this for a little while as I'm on holiday and have some exams coming up.

**Comment by stancubed** [comment]
Enjoy your holiday! Is there any way to force the correct type by what I'm passing into the method or is it just broken for now?

For anybody else finding/tracking this, a workaround I've implemented (for my own use case) is to use the naked .get_series() call to receive all series and have them in a variable for use with other calls. All I'm trying to do is get the Series Title for any upcoming episode (sucks that it's not in the response so you have to make 2 calls) so my code looks like this:

```
    series_list = sonarr.get_series()
    forecast = sonarr.get_calendar(start_date=start.strftime("%Y-%m-%d"),end_date=end.strftime("%Y-%m-%d"))
    
    for episode in forecast:
        series = [item for item in series_list if item['id']==episode['seriesId']]
        data = episode
        data['seriesTitle'] = series[0]['title']
        # And so on...
```

**Comment by Archmonger** [comment]
@marksie1988 We should probably yank the broken releases from PyPI.

**Comment by marksie1988** [comment]
Yes I have now yanked those versions.
